apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Cloud-Automation-Cafe
  description: |
    A Cloud-agnostic solution that address automation of the entire Cloud spectrum 
  links:
    - url: http://13.51.108.185:3000/login
      title: Cloud Automation Cafe
      icon: website
  annotations:
    jenkins.io/job-full-name: cac-application/aws-cac-test
spec:
  type: other
  lifecycle: unknown
  owner: backstage
