apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: aws-cac-test
  annotations:
    github.com/project-slug: porasm1998/aws-cac-test
spec:
  type: other
  lifecycle: unknown
  owner: backstage
