const CONSTANT = {
    PASSWORD_REGEX: /^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*?[#?!@$%^&*-]).{8,20}$/,
    EMAIL_REGEX: /^[^\s@]+@[^\s@]+\.[^\s@]+$/,
    PHONE_NUMBER_REGEX: /^(\+?\d{1,4}[\s-])?(?!0+\s+,?$)(?=.*\d{4,10}$)/
}

const STANDARD_CONTROL_CATEGORIES = {
    REGION: 'Region',
    VPC: 'Vpc',
    SECURITY_GROUP: 'Security_Group',
    SUBNET_NAME: 'Subnet',
    KEY_NAME: 'Key_Name',
    SNS_TOPIC_NAME: 'Sns_Topic',
    INSTANCE_SCHEDULE: 'Instance_Schedule',
    BACKUP: 'Backup_Plan',
    EBS_VOLUME_TYPE: 'EBS_Volume_Type',
    IAM_PROFILE: 'IAM_Profile',
    INSTANCE_TYPE: 'Instance_Type',
    AMI: 'AMI',
    AMI_Hardening: 'AMI_Hardening',
    EC2_TAGS: 'Ec2_Tag',
    AMI_SCRIPTS_FOLDER: 'AMI_Scripts_Folder',
    AMI_SCRIPTS_FILE: 'AMI_Scripts_File',
    AZ: 'AZ',
    AMI_TYPE: 'AMI_Type',
    EC2_INSTANCE: 'Ec2_Instance',
    LOADBALANCER_TYPE: 'LoadBalancer_Type',
    PROTOCOL: 'Protocol',
    DB_ENGINE: 'Db_Engine',
    DB_ENGINE_VERSION: 'Db_Engine_Version',
    DB_SUBNETGROUPNAME: 'Db_Subnetgroupname',
    DB_INSTANCE_CLASS: 'Db_Instance_Class',
    STORAGE_THRESHOLD: 'Storage_Threshold',
    CPU_UTILIZATION_THRESHOLD: 'cpu_utilization_threshold',
    STATISTIC_PERIOD: 'statistic_period',
    EVALUATION_PERIOD: 'evaluation_period',
    SECRETS_MANAGER: 'Secrets_Manager',
    EMR_TAGS: 'Emr_Tag',
    NODE_TYPE: 'Node_Type',
    DATA_POINTS_TO_ALARM: 'Data_Points_To_Alarm',
    SNAPSHOT_SCHEDULE: 'Snapshot_Schedule',
    NODES: 'Nodes',
    ALLOCATION_ID: 'Allocation_Id',
    TIER: 'Tier',
    CONNECT_MODE: 'Connect_Mode',
    ADDRESS_TYPE: 'Address_Type',
    SCHEMA_TYPE: 'Schema_Type',
    PARENT_RESOURCE_TYPE: 'Parent_Resource_Type',
    EKS_ENGINE: 'Eks_Engine',
    BOOLEAN: 'Boolean',
    AZURE_REGION: 'Azure_Region',
    ZONE: 'Zone',
    CIDR: 'CIDR',
}

const DropDownList = [
    'Region',
    'Vpc',
    'Security_Group',
    'Subnet',
    'Key_Name',
    'Sns_Topic',
    'Instance_Schedule',
    'Backup_Plan',
    'EBS_Volume_Type',
    'IAM_Profile',
    'Instance_Type',
    'AMI',
    'AMI_Hardening',
    'Ec2_Tag',
    'AMI_Scripts_Folder',
    'AMI_Scripts_File',
    'AZ',
    'AMI_Type',
    'Ec2_Instance',
    'LoadBalancer_Type',
    'Protocol',
    'Db_Engine',
    'Db_Engine_Version',
    'Db_Subnetgroupname',
    'Db_Instance_Class',
    'Storage_Threshold',
    'cpu_utilization_threshold',
    'statistic_period',
    'evaluation_period',
    'Secrets_Manager',
    'Emr_Tag',
    'Node_Type',
    'Data_Points_To_Alarm',
    'Snapshot_Schedule',
    'Nodes',
    'Allocation_Id',
    'Tier',
    'Connect_Mode',
    'Address_Type',
    'Schema_Type',
    'Parent_Resource_Type',
    'Eks_Engine',
    'Boolean',
    'Azure_Region',
    'Zone',
    'CIDR',
]

export { CONSTANT, STANDARD_CONTROL_CATEGORIES, DropDownList };